debug: true

server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 50
        max-wait: -1s
        max-idle: 50
        min-idle: 1
    timeout: 300ms
